# Ch04 NumPy 數值計算 進階

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

## 隨機函數
- np.random.rand(dim0\[, dim1, dim2, ...\])
- np.random.randint(low, high=None, size=None)
- 參考資料: 
  - [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
  - [python numpy 常用随机数的产生方法](https://blog.csdn.net/m0_37804518/article/details/78490709)

In [3]:
'''
np.random.seed(42)
numpy.random.rand(): 設定種子後，取得隨機亂數

註: np.random.seed() 的引數固定，隨機產生的值也會固定，亂數的值介於 [0, 1)
'''
np.random.seed(23)
a = np.random.rand(3); a

array([0.51729788, 0.9469626 , 0.76545976])

In [ ]:
'''
np.random.randint(start, end - 1, size=數量): 產生 start 到 end - 1 之間的整數值

隨機產生 100 位同學的成績
'''
a = np.random.randint(0, 100, size=(1,100), dtype='int32'); a # (1, 100) 即二維，亦可 (2, 3, 4) 即三維

# np.array((2,4))


array([[22, 87, 66, 82, 63,  1, 97, 55,  1, 96, 57, 72, 51, 48, 63, 34,
        64, 69, 89, 83, 29, 42, 28, 95, 69,  2, 81, 47, 23, 59, 67, 77,
        32, 55, 39, 69, 68,  7, 97, 47,  3, 73, 60, 41, 44, 99, 72,  6,
        38, 49, 17, 72, 76, 30, 31, 53, 16, 66, 41, 76, 20, 49,  7, 90,
        18, 95, 85, 53,  7, 44, 47, 61, 14, 69,  4, 94, 62, 63,  1, 37,
        91, 65, 85, 64, 99,  9, 74, 69, 15,  3, 22, 69, 26, 60,  5,  3,
        14, 40, 85, 51]], dtype=int32)

In [5]:
'''
np.random.shuffle(): 陣列元素重新排列
'''
x = np.arange(10)
np.random.shuffle(x)
x

array([7, 4, 8, 6, 9, 1, 3, 5, 2, 0])

## 統計運算

### 平均 mean()

In [6]:
# mean(): 元素平均值 - 1D
x = np.array([[1, 2, 3, 4]])
np.mean(x)

np.float64(2.5)

In [7]:
# mean(): 元素平均值 - 2D
x = np.array([[1, 2], [3, 4]])
np.mean(x)

np.float64(2.5)

In [8]:
# mean() 加上 axis
x = np.array([[1, 2], [3, 4]])
np.mean(x, axis = 0)

array([2., 3.])

### 中位數 median()

In [9]:
# median(): 中位數
x = np.array([[12, 7, 4], [3, 2, 6]])
np.median(x)

np.float64(5.0)

In [10]:
# median() 加上 axis
np.median(x, axis = 0)

array([7.5, 4.5, 5. ])

### 變異數 var()

In [11]:
# var(): 變異數 (variance) (離散隨機變數) (一維陣列)
'''
import math
mean = (1 + 2 + 3 + 4) / 4
(math.pow(1 - mean, 2) + math.pow(2 - mean, 2) + math.pow(3 - mean, 2) + math.pow(4 - mean, 2)) / 4

補充: var() 也可以設定 axis
'''
x = np.array([1, 2, 3, 4])
np.var(x)

np.float64(1.25)

In [12]:
# var(): 變異數 (variance) (離散隨機變數) (二維陣列)
'''
import math

x_ = x.ravel()
mean_X = np.mean(x_)
sum = 0

for i in x_:
    sum += math.pow(i-mean_X, 2)

sum / len(x_)
'''

x = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])
np.var(x)



np.float64(4.6875)

### 標準差 var()

In [13]:
# std(): 標準差 (standard deviation) - 1D array
'''
變異數 = 「標準差」的平方
標準差 = 「變異數」開根號
'''

x = np.array([1, 2, 3, 4])
np.std(x)

np.float64(1.118033988749895)

In [14]:
# std(): 標準差 (standard deviation) - 2D array
x = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])
np.std(x)

np.float64(2.165063509461097)

In [15]:
# std() 加上 axis
np.std(x, axis=0)

array([0.5, 1. , 1.5, 2. ])

### 累計加總 cumsum()

In [16]:
# 1D Array
x = np.arange(10)

np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
# 2D Array
# -1，不指定維度，自動給
x = np.arange(10).reshape(2,-1); x

# np.cumsum(x)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
np.cumsum(x, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]])

In [19]:
np.cumsum(x, axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13]])

## 邏輯運算

### any()

In [20]:
# 一個滿足就返回 True
ar=np.array([9, 9, 4, 7])
np.any((ar%7)==0)

np.True_

### all()

In [21]:
# 全部為真才返回 True
ar=np.array([9, 9, 4, 7])
np.all((ar%7)==0)

np.False_

In [22]:
ar=np.array([7, 14, 28, 35])
np.all((ar%7)==0)

np.True_

## 廣播 Broadcasting

執行 2 個陣列運算時，原則上必須外形相同才能運算，如果不同，可以使用廣播 (broadcasting) 機制，將小陣列「擴大」到兩個陣列都相同，之後再進行運算。

![Computation on Arrays: Broadcasting](https://i.imgur.com/CuB6Bsh.png)
參考資料: [Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [23]:
ar=np.ones((3,2)); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
ar2=np.array([2,3]); ar2

array([2, 3])

In [25]:
# 缺失維度自動補滿
ar + ar2

array([[3., 4.],
       [3., 4.],
       [3., 4.]])

### Broadcasting works across dimensions

In [26]:
ar=np.array([[23,24,25]]); ar

array([[23, 24, 25]])

In [27]:
ar.T

array([[23],
       [24],
       [25]])

In [28]:
ar.T+ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])